
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Replace this with the path to your WebDriver (e.g., ChromeDriver)
webdriver_path = '/Users/adamtaheri/Downloads/chromedriver_mac_arm64'

# List of websites to scan
websites = [
    'https://www.ibba.org/broker-profile/california/modesto/ralph-carrasco/',
'https://www.ibba.org/broker-profile/california/san-francisco/ellen-hui/',
'https://www.ibba.org/broker-profile/california/san-francisco/keith-ryan/',
'https://www.ibba.org/broker-profile/california/newark/vijay-sher/',
'https://www.ibba.org/broker-profile/california/san-francisco/antoinette-payne/',
'https://www.ibba.org/broker-profile/california/el-sobrabte/manjit-singh/',
'https://www.ibba.org/broker-profile/california/san-francisco/matt-cohen/',
'https://www.ibba.org/broker-profile/california/berkeley/jeffrey-weinstein/',
'https://www.ibba.org/broker-profile/california/elk-grove/joseph-cervantes/',
'https://www.ibba.org/broker-profile/california/san-jose/farley-gouner/',
'https://www.ibba.org/broker-profile/california/larkspur/kris-moe/',
'https://www.ibba.org/broker-profile/california/san-rafael/shaman-ajmani/',
'https://www.ibba.org/broker-profile/california/san-francisco/joh-olson/',
'https://www.ibba.org/broker-profile/california/campbell/john-burgess/',
'https://www.ibba.org/broker-profile/california/san-ramon/take-iga/',
'https://www.ibba.org/broker-profile/california/san-francisco/patrick-totah/',
'https://www.ibba.org/broker-profile/california/san-ramon/christopher-vogt/',
'https://www.ibba.org/broker-profile/california/sacramento/tricia-bernhardt/',
'https://www.ibba.org/broker-profile/california/modesto/lee-grover/',
'https://www.ibba.org/broker-profile/california/sebastopol/joseph-tucker/',
'https://www.ibba.org/broker-profile/california/cameron-park/michelle-mendenhall/',
'https://www.ibba.org/broker-profile/california/san-mateo/ken-berry/',
'https://www.ibba.org/broker-profile/california/campbell/john-mittelstet/',
'https://www.ibba.org/broker-profile/california/pleasanton/richard-matusich/',
'https://www.ibba.org/broker-profile/california/walnut-creek/antoinette-norris/',
'https://www.ibba.org/broker-profile/california/santa-rosa/michele-habeeb/',
'https://www.ibba.org/broker-profile/california/roseville/robert-altieri/',
'https://www.ibba.org/broker-profile/nevada/reno/kelly-higgins/',
'https://www.ibba.org/broker-profile/california/visalia/bradley-bickers/',
'https://www.ibba.org/broker-profile/california/san-jose/kevin-quang-lam/',
'https://www.ibba.org/broker-profile/california/auburn/leslie-horton/',
'https://www.ibba.org/broker-profile/california/aptos/kenneth-johnson/',
'https://www.ibba.org/broker-profile/california/san-francisco/andy-mirabell/',
'https://www.ibba.org/broker-profile/california/sacramento/scott-weavil/',
'https://www.ibba.org/broker-profile/california/orangevale/david-lapinski-cbb/',
'https://www.ibba.org/broker-profile/california/san-francisco/jack-chung/',
'https://www.ibba.org/broker-profile/california/fremont/shailendra-gupta/',
'https://www.ibba.org/broker-profile/california/pleasanton/harmit-toor/',
'https://www.ibba.org/broker-profile/california/palo-alto/tim-cunha/',
'https://www.ibba.org/broker-profile/california/graeagle/mark-smith/',
'https://www.ibba.org/broker-profile/california/concord/ron-schwab/',
'https://www.ibba.org/broker-profile/california/carmichael/todd-eichman/',
'https://www.ibba.org/broker-profile/california/san-rafael/jim-pate/',
'https://www.ibba.org/broker-profile/california/danville/gary-ware/',
'https://www.ibba.org/broker-profile/nevada/reno/kurt-okraski/',
'https://www.ibba.org/broker-profile/california/pleasant-hill/james-marshall/',
'https://www.ibba.org/broker-profile/california/san-ramon/george-hashimoto/',
'https://www.ibba.org/broker-profile/california/san-jose/linda-lu/',
'https://www.ibba.org/broker-profile/california/san-jose/jordan-zweigoron/',
'https://www.ibba.org/broker-profile/california/lincoln/christopher-kelly/',
'https://www.ibba.org/broker-profile/california/manteca/eldon-regua/',
'https://www.ibba.org/broker-profile/california/san-francisco/lloyd-silver/',
'https://www.ibba.org/broker-profile/california/el-dorado-hills/brett-sargent/',
'https://www.ibba.org/broker-profile/california/soquel/datta-khalsa/',
'https://www.ibba.org/broker-profile/california/sacramento/jim-amen/',
'https://www.ibba.org/broker-profile/california/los-gatos/douglas-atkinson/',
'https://www.ibba.org/broker-profile/california/fresno/leo-landaverde/',
'https://www.ibba.org/broker-profile/california/novato/allen-coddington/',
'https://www.ibba.org/broker-profile/california/roseville/joel-higginbotham/',
'https://www.ibba.org/broker-profile/california/redwood-city/david-halvorson/',
'https://www.ibba.org/broker-profile/california/santa-clara/helena-li/',
'https://www.ibba.org/broker-profile/california/fairfield/din-sharma/',
'https://www.ibba.org/broker-profile/california/roseville/michael-ebuen/',
'https://www.ibba.org/broker-profile/california/modesto/stuart-gilman/',
'https://www.ibba.org/broker-profile/california/sacramento/ujjal-singh/',
'https://www.ibba.org/broker-profile/california/modesto/harpreet-singh/',
'https://www.ibba.org/broker-profile/california/san-jose/fred-king/',
'https://www.ibba.org/broker-profile/nevada/reno/stewart-guthrie/',
'https://www.ibba.org/broker-profile/california/millbrae/mario-west/',
'https://www.ibba.org/broker-profile/california/petaluma/roy-martinez/',
'https://www.ibba.org/broker-profile/california/san-mateo/michael-mogin/',
'https://www.ibba.org/broker-profile/california/campbell/greg-carpenter/',
'https://www.ibba.org/broker-profile/california/pleasanton/norris-domingue/',
'https://www.ibba.org/broker-profile/california/campbell/sandeep-dilwali/',
'https://www.ibba.org/broker-profile/california/el-dorado-hills/bill-wright/',
'https://www.ibba.org/broker-profile/california/petaluma/louis-cionci/',
'https://www.ibba.org/broker-profile/california/san-mateo/tommy-tran/',
'https://www.ibba.org/broker-profile/california/fresno/scott-morales/',
'https://www.ibba.org/broker-profile/california/santa-clara/kaiden-degas/',
'https://www.ibba.org/broker-profile/california/walnut-creek/shifang-sun/',
'https://www.ibba.org/broker-profile/california/half-moon-bay/janet-lawson/',
'https://www.ibba.org/broker-profile/california/salinas/stephen-schaub/',
'https://www.ibba.org/broker-profile/california/san-luis-obispo/daniel-mcgee/',
'https://www.ibba.org/broker-profile/california/san-francisco/cynthia-randall/',
'https://www.ibba.org/broker-profile/california/san-rafael/aref-ahmadia/',
'https://www.ibba.org/broker-profile/california/modesto/jesson-wajdowicz/',
'https://www.ibba.org/broker-profile/california/roseville/charles-fox/',
'https://www.ibba.org/broker-profile/california/folsom/brian-serina/',
'https://www.ibba.org/broker-profile/california/fremont/harry-sidhu/',
'https://www.ibba.org/broker-profile/california/modesto/ricky-lininger/',
'https://www.ibba.org/broker-profile/california/pleasanton/bhagdeep-dhaliwal/',
'https://www.ibba.org/broker-profile/california/san-jose/brian-bacher/',
'https://www.ibba.org/broker-profile/california/san-francisco/richard-waxman/',
'https://www.ibba.org/broker-profile/california/san-jose/ajay-singh/',
'https://www.ibba.org/broker-profile/california/modesto/rodney-cordova/',
'https://www.ibba.org/broker-profile/california/santa-clara/rick-boon-beng-teh/',
'https://www.ibba.org/broker-profile/california/campbell/bernie-nijjar/',
'https://www.ibba.org/broker-profile/california/sacramento/terry-watts/',
'https://www.ibba.org/broker-profile/california/sacramento/luke-middendorf/',
'https://www.ibba.org/broker-profile/california/carmel-by-the-sea/james-herlihy/',
'https://www.ibba.org/broker-profile/california/discovery-bay/stan-cortland/',
'https://www.ibba.org/broker-profile/california/santa-rosa/allen-cox/',
'https://www.ibba.org/broker-profile/california/fresno/jaspal-jas-gahunia/',
'https://www.ibba.org/broker-profile/california/modesto/jay-grover/',
'https://www.ibba.org/broker-profile/california/san-francisco/richard-kim/',
'https://www.ibba.org/broker-profile/california/cupertino/soo-kong-lim/',
'https://www.ibba.org/broker-profile/california/roseville/randy-hendershot/',
'https://www.ibba.org/broker-profile/california/campbell/paul-lau/',
'https://www.ibba.org/broker-profile/california/pleasanton/raj-sathyaseelan/',
'https://www.ibba.org/broker-profile/california/pittsburg/anil-sharma/',
'https://www.ibba.org/broker-profile/california/petaluma/al-statz/',
'https://www.ibba.org/broker-profile/california/carmichael/dalip-gupta/',
'https://www.ibba.org/broker-profile/california/campbell/ian-maclachlan/',
'https://www.ibba.org/broker-profile/california/folsom/sam-lee/',
'https://www.ibba.org/broker-profile/california/santa-clara/helen-zhengyu-liu/',
'https://www.ibba.org/broker-profile/california/pleasanton/murali-barathi/',
'https://www.ibba.org/broker-profile/california/el-dorado-hills/robert-wellman/',
'https://www.ibba.org/broker-profile/california/rocklin/roy-fruehauf-jr/',
'https://www.ibba.org/broker-profile/california/campbell/clarence-stone/',
'https://www.ibba.org/broker-profile/california/roseville/bill-garcia/',
'https://www.ibba.org/broker-profile/california/pleasanton/narender-taneja/',
'https://www.ibba.org/broker-profile/california/san-francisco/doug-whitmire/',
'https://www.ibba.org/broker-profile/california/roseville/wes-brown/',
'https://www.ibba.org/broker-profile/california/manteca/nhung-trieu/',
'https://www.ibba.org/broker-profile/california/san-francisco/norman-pearce/',
'https://www.ibba.org/broker-profile/california/petaluma/donald-ross/',
'https://www.ibba.org/broker-profile/california/santa-rosa/michael-nova/',
'https://www.ibba.org/broker-profile/california/san-jose/charles-trimmier/',
'https://www.ibba.org/broker-profile/california/redding/gerald-bendix/',
'https://www.ibba.org/broker-profile/california/sunnyvale/bruce-martin/',
'https://www.ibba.org/broker-profile/nevada/reno/lisamarie-wand/',
'https://www.ibba.org/broker-profile/california/campbell/ray-rojas/',
'https://www.ibba.org/broker-profile/california/aptos/rex-walters/',
'https://www.ibba.org/broker-profile/california/monterey/flora-chong/',
'https://www.ibba.org/broker-profile/california/walnut-creek/matt-sadati/',
'https://www.ibba.org/broker-profile/california/san-jose/huy-han/',
'https://www.ibba.org/broker-profile/california/santa-cruz/john-lamay/',
'https://www.ibba.org/broker-profile/california/carmel/david-house/',
'https://www.ibba.org/broker-profile/california/burlingame/nicolas-zhao/',
'https://www.ibba.org/broker-profile/california/benicia/joseph-miesch/',
'https://www.ibba.org/broker-profile/california/el-dorado-hills/william-davies/',
'https://www.ibba.org/broker-profile/california/santa-clara/diane-ho/',
'https://www.ibba.org/broker-profile/california/pleasant-hill/tony-moran/',
'https://www.ibba.org/broker-profile/california/livermore/rich-buckley/',
'https://www.ibba.org/broker-profile/california/campbell/ifti-ahmed/',
'https://www.ibba.org/broker-profile/california/san-jose/shannon-ye/',
'https://www.ibba.org/broker-profile/california/san-francisco/randy-katz/',
'https://www.ibba.org/broker-profile/california/san-jose/m-nikoo/',
'https://www.ibba.org/broker-profile/california/sacramento/michael-langford/'
]

# Initialize the WebDriver
chrome_service = ChromeService(executable_path=webdriver_path)
driver = webdriver.Chrome(service=chrome_service)

for website in websites:
    driver.get(website)
    try:
        # Wait for the target element to load
        icon_element = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.XPATH, '//i[contains(@class, "material-icons") and contains(text(), "email")]'))
        )
        email_element = icon_element.find_element(By.XPATH, './following-sibling::a')
        email = email_element.text
        print(f'Email from {website}: {email}')
    except Exception as e:
        print(f'Error for {website}: {e}')

# Close the WebDriver
driver.quit()
